# Generated by Django 6.0.7 on 2026-08-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_videw_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='username',
            name='vid',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='username',
        ),
        migrations.DeleteModel(
            name='Videw',
        ),
    ]
