# Generated by Django 6.0.7 on 2026-08-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product Name', max_length=100)),
                ('content', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(default='photos/26/08/09/9.png', upload_to='photos/%y/%m/%d', verbose_name='photo')),
                ('condition', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('phone', 'phone'), ('computer', 'computer')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'product',
                'ordering': ['name'],
            },
        ),
    ]
