# Generated by Django 6.0.7 on 2026-08-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_test_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
